# Generated by Django 5.1.6 on 2025-07-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="stock",
            field=models.IntegerField(null=True),
        ),
    ]
