# Generated by Django 5.1.6 on 2025-07-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_item_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="stock",
            field=models.IntegerField(default=100),
        ),
    ]
