# Generated by Django 5.1.6 on 2025-07-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
